esphome:
  name: wemosd1mini
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "isi nama wifi"
  password: "isi pw"

  # # Optional manual IP
  # manual_ip:
  #   static_ip: 192.168.1.100
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0

logger:

# api:

# ota:

web_server:
  port: 80

switch:
  - platform: gpio
    name: "Relay"
    pin: D1
